version: '3.8'

services:
  photo-svc:
    image: hervipro/be-yourmoments:photo-svc
    env_file:
      - .env.photo
    ports:
      - "8001:8001"
    networks:
      - backend
    depends_on:
      - postgres
      - consul
      - nats

  transaction-svc:
    image: hervipro/be-yourmoments:transaction-svc
    env_file:
      - .env.transaction
    ports:
      - "8005:8005"
    networks:
      - backend
    depends_on:
      - redis
      - postgres
      - consul
      - nats

  upload-svc:
    image: hervipro/be-yourmoments:upload-svc
    env_file:
      - .env.upload
    ports:
      - "8002:8002"
    networks:
      - backend
    depends_on:
      - minio
      - consul
      - nats

  user-svc:
    image: hervipro/be-yourmoments:user-svc
    env_file:
      - .env.user
    volumes:
      - ./user-svc/serviceAccountKey.json:/app/serviceAccountKey.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json
    ports:
      - "8003:8003"
    networks:
      - backend
    depends_on:
      - redis
      - postgres
      - consul
      - nats


  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "6379"  # Hanya untuk internal



  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend
    expose:
      - "5432"

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - backend

  nats:
    image: nats:2.11.2-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - backend
    command: ["-js", "-m", "8222"]

  consul:
    image: hashicorp/consul:1.20.6
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  minio-data: