// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pb/ai/ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url              string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	OriginalFilename string `protobuf:"bytes,3,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
}

func (x *ProcessPhotoRequest) Reset() {
	*x = ProcessPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPhotoRequest) ProtoMessage() {}

func (x *ProcessPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPhotoRequest.ProtoReflect.Descriptor instead.
func (*ProcessPhotoRequest) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPhotoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessPhotoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProcessPhotoRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type ProcessPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProcessPhotoResponse) Reset() {
	*x = ProcessPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPhotoResponse) ProtoMessage() {}

func (x *ProcessPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPhotoResponse.ProtoReflect.Descriptor instead.
func (*ProcessPhotoResponse) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPhotoResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessPhotoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProcessFacecamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ProcessFacecamRequest) Reset() {
	*x = ProcessFacecamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessFacecamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFacecamRequest) ProtoMessage() {}

func (x *ProcessFacecamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFacecamRequest.ProtoReflect.Descriptor instead.
func (*ProcessFacecamRequest) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessFacecamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessFacecamRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ProcessFacecamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProcessFacecamResponse) Reset() {
	*x = ProcessFacecamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessFacecamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFacecamResponse) ProtoMessage() {}

func (x *ProcessFacecamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFacecamResponse.ProtoReflect.Descriptor instead.
func (*ProcessFacecamResponse) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessFacecamResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessFacecamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AIBulkPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId string `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
}

func (x *AIBulkPhoto) Reset() {
	*x = AIBulkPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIBulkPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIBulkPhoto) ProtoMessage() {}

func (x *AIBulkPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIBulkPhoto.ProtoReflect.Descriptor instead.
func (*AIBulkPhoto) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AIBulkPhoto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIBulkPhoto) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type AIPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompressedUrl    string `protobuf:"bytes,5,opt,name=compressed_url,json=compressedUrl,proto3" json:"compressed_url,omitempty"`
	CollectionUrl    string `protobuf:"bytes,6,opt,name=collection_url,json=collectionUrl,proto3" json:"collection_url,omitempty"`
	OriginalFilename string `protobuf:"bytes,7,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
}

func (x *AIPhoto) Reset() {
	*x = AIPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIPhoto) ProtoMessage() {}

func (x *AIPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIPhoto.ProtoReflect.Descriptor instead.
func (*AIPhoto) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AIPhoto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIPhoto) GetCompressedUrl() string {
	if x != nil {
		return x.CompressedUrl
	}
	return ""
}

func (x *AIPhoto) GetCollectionUrl() string {
	if x != nil {
		return x.CollectionUrl
	}
	return ""
}

func (x *AIPhoto) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type ProcessBulkPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessBulkAi *AIBulkPhoto `protobuf:"bytes,1,opt,name=process_bulk_ai,json=processBulkAi,proto3" json:"process_bulk_ai,omitempty"`
	ProcessAi     []*AIPhoto   `protobuf:"bytes,2,rep,name=process_ai,json=processAi,proto3" json:"process_ai,omitempty"`
}

func (x *ProcessBulkPhotoRequest) Reset() {
	*x = ProcessBulkPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessBulkPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBulkPhotoRequest) ProtoMessage() {}

func (x *ProcessBulkPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBulkPhotoRequest.ProtoReflect.Descriptor instead.
func (*ProcessBulkPhotoRequest) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessBulkPhotoRequest) GetProcessBulkAi() *AIBulkPhoto {
	if x != nil {
		return x.ProcessBulkAi
	}
	return nil
}

func (x *ProcessBulkPhotoRequest) GetProcessAi() []*AIPhoto {
	if x != nil {
		return x.ProcessAi
	}
	return nil
}

type ProcessBulkPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ProcessBulkPhotoResponse) Reset() {
	*x = ProcessBulkPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_ai_ai_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessBulkPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBulkPhotoResponse) ProtoMessage() {}

func (x *ProcessBulkPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ai_ai_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBulkPhotoResponse.ProtoReflect.Descriptor instead.
func (*ProcessBulkPhotoResponse) Descriptor() ([]byte, []int) {
	return file_pb_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessBulkPhotoResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessBulkPhotoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pb_ai_ai_proto protoreflect.FileDescriptor

var file_pb_ai_ai_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x61, 0x69, 0x2f, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x61, 0x69, 0x22, 0x64, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2b, 0x0a,
	0x11, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x39, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x63, 0x65, 0x63,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x46, 0x0a, 0x16, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x63, 0x65, 0x63, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0b, 0x41, 0x49, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x22, 0x94, 0x01, 0x0a, 0x07, 0x41, 0x49, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x2b, 0x0a, 0x11, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7e, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x62,
	0x75, 0x6c, 0x6b, 0x5f, 0x61, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61,
	0x69, 0x2e, 0x41, 0x49, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x41, 0x69, 0x12, 0x2a, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x61, 0x69, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x61, 0x69, 0x2e, 0x41, 0x49, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x69, 0x22, 0x48, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xe6, 0x01, 0x0a, 0x09, 0x41, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x12, 0x17, 0x2e, 0x61, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x69, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61,
	0x63, 0x65, 0x63, 0x61, 0x6d, 0x12, 0x19, 0x2e, 0x61, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x46, 0x61, 0x63, 0x65, 0x63, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x46, 0x61, 0x63,
	0x65, 0x63, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x10,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x2e, 0x61, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x75, 0x6c,
	0x6b, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x61, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x69, 0x3b, 0x61, 0x69, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_ai_ai_proto_rawDescOnce sync.Once
	file_pb_ai_ai_proto_rawDescData = file_pb_ai_ai_proto_rawDesc
)

func file_pb_ai_ai_proto_rawDescGZIP() []byte {
	file_pb_ai_ai_proto_rawDescOnce.Do(func() {
		file_pb_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_ai_ai_proto_rawDescData)
	})
	return file_pb_ai_ai_proto_rawDescData
}

var file_pb_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_ai_ai_proto_goTypes = []interface{}{
	(*ProcessPhotoRequest)(nil),      // 0: ai.ProcessPhotoRequest
	(*ProcessPhotoResponse)(nil),     // 1: ai.ProcessPhotoResponse
	(*ProcessFacecamRequest)(nil),    // 2: ai.ProcessFacecamRequest
	(*ProcessFacecamResponse)(nil),   // 3: ai.ProcessFacecamResponse
	(*AIBulkPhoto)(nil),              // 4: ai.AIBulkPhoto
	(*AIPhoto)(nil),                  // 5: ai.AIPhoto
	(*ProcessBulkPhotoRequest)(nil),  // 6: ai.ProcessBulkPhotoRequest
	(*ProcessBulkPhotoResponse)(nil), // 7: ai.ProcessBulkPhotoResponse
}
var file_pb_ai_ai_proto_depIdxs = []int32{
	4, // 0: ai.ProcessBulkPhotoRequest.process_bulk_ai:type_name -> ai.AIBulkPhoto
	5, // 1: ai.ProcessBulkPhotoRequest.process_ai:type_name -> ai.AIPhoto
	0, // 2: ai.AiService.ProcessPhoto:input_type -> ai.ProcessPhotoRequest
	2, // 3: ai.AiService.ProcessFacecam:input_type -> ai.ProcessFacecamRequest
	6, // 4: ai.AiService.ProcessBulkPhoto:input_type -> ai.ProcessBulkPhotoRequest
	1, // 5: ai.AiService.ProcessPhoto:output_type -> ai.ProcessPhotoResponse
	3, // 6: ai.AiService.ProcessFacecam:output_type -> ai.ProcessFacecamResponse
	7, // 7: ai.AiService.ProcessBulkPhoto:output_type -> ai.ProcessBulkPhotoResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_ai_ai_proto_init() }
func file_pb_ai_ai_proto_init() {
	if File_pb_ai_ai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_ai_ai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessFacecamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessFacecamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIBulkPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AIPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessBulkPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_ai_ai_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessBulkPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_ai_ai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_ai_ai_proto_goTypes,
		DependencyIndexes: file_pb_ai_ai_proto_depIdxs,
		MessageInfos:      file_pb_ai_ai_proto_msgTypes,
	}.Build()
	File_pb_ai_ai_proto = out.File
	file_pb_ai_ai_proto_rawDesc = nil
	file_pb_ai_ai_proto_goTypes = nil
	file_pb_ai_ai_proto_depIdxs = nil
}
