// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/user.proto

package userpb

import (
	photo "github.com/hervibest/be-yourmoments-backup/pb/photo"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// google.protobuf.Timestamp
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthenticateResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// *
// Authenticate V2 (Improved JWT )
type AuthenticateRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequestV2) Reset() {
	*x = AuthenticateRequestV2{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequestV2) ProtoMessage() {}

func (x *AuthenticateRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequestV2.ProtoReflect.Descriptor instead.
func (*AuthenticateRequestV2) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateRequestV2) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateRequestV2) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateRequestV2) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AuthenticateResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponseV2) Reset() {
	*x = AuthenticateResponseV2{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponseV2) ProtoMessage() {}

func (x *AuthenticateResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponseV2.ProtoReflect.Descriptor instead.
func (*AuthenticateResponseV2) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateResponseV2) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthenticateResponseV2) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthenticateResponseV2) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Similarity    uint32                 `protobuf:"varint,5,opt,name=similarity,proto3" json:"similarity,omitempty"`
	CreatorId     string                 `protobuf:"bytes,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,7,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetSimilarity() uint32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *User) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *User) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type SendBulkNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountMap      map[string]int32       `protobuf:"bytes,1,rep,name=count_map,json=countMap,proto3" json:"count_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationRequest) Reset() {
	*x = SendBulkNotificationRequest{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationRequest) ProtoMessage() {}

func (x *SendBulkNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendBulkNotificationRequest) GetCountMap() map[string]int32 {
	if x != nil {
		return x.CountMap
	}
	return nil
}

type SendBulkNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationResponse) Reset() {
	*x = SendBulkNotificationResponse{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationResponse) ProtoMessage() {}

func (x *SendBulkNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *SendBulkNotificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendBulkNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendBulkPhotoNotificationRequest struct {
	state                protoimpl.MessageState        `protogen:"open.v1"`
	BulkUserSimilarPhoto []*photo.BulkUserSimilarPhoto `protobuf:"bytes,1,rep,name=bulk_user_similar_photo,json=bulkUserSimilarPhoto,proto3" json:"bulk_user_similar_photo,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SendBulkPhotoNotificationRequest) Reset() {
	*x = SendBulkPhotoNotificationRequest{}
	mi := &file_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkPhotoNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkPhotoNotificationRequest) ProtoMessage() {}

func (x *SendBulkPhotoNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkPhotoNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBulkPhotoNotificationRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *SendBulkPhotoNotificationRequest) GetBulkUserSimilarPhoto() []*photo.BulkUserSimilarPhoto {
	if x != nil {
		return x.BulkUserSimilarPhoto
	}
	return nil
}

type SendBulkPhotoNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkPhotoNotificationResponse) Reset() {
	*x = SendBulkPhotoNotificationResponse{}
	mi := &file_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkPhotoNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkPhotoNotificationResponse) ProtoMessage() {}

func (x *SendBulkPhotoNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkPhotoNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendBulkPhotoNotificationResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *SendBulkPhotoNotificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendBulkPhotoNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendSinglePhotoNotificationRequest struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	UserSimilarPhoto []*photo.UserSimilarPhoto `protobuf:"bytes,1,rep,name=user_similar_photo,json=userSimilarPhoto,proto3" json:"user_similar_photo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendSinglePhotoNotificationRequest) Reset() {
	*x = SendSinglePhotoNotificationRequest{}
	mi := &file_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSinglePhotoNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSinglePhotoNotificationRequest) ProtoMessage() {}

func (x *SendSinglePhotoNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSinglePhotoNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendSinglePhotoNotificationRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *SendSinglePhotoNotificationRequest) GetUserSimilarPhoto() []*photo.UserSimilarPhoto {
	if x != nil {
		return x.UserSimilarPhoto
	}
	return nil
}

type SendSinglePhotoNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSinglePhotoNotificationResponse) Reset() {
	*x = SendSinglePhotoNotificationResponse{}
	mi := &file_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSinglePhotoNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSinglePhotoNotificationResponse) ProtoMessage() {}

func (x *SendSinglePhotoNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSinglePhotoNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendSinglePhotoNotificationResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *SendSinglePhotoNotificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendSinglePhotoNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendSingleFacecamNotificationRequest struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	UserSimilarPhoto []*photo.UserSimilarPhoto `protobuf:"bytes,1,rep,name=user_similar_photo,json=userSimilarPhoto,proto3" json:"user_similar_photo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendSingleFacecamNotificationRequest) Reset() {
	*x = SendSingleFacecamNotificationRequest{}
	mi := &file_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSingleFacecamNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSingleFacecamNotificationRequest) ProtoMessage() {}

func (x *SendSingleFacecamNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSingleFacecamNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendSingleFacecamNotificationRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *SendSingleFacecamNotificationRequest) GetUserSimilarPhoto() []*photo.UserSimilarPhoto {
	if x != nil {
		return x.UserSimilarPhoto
	}
	return nil
}

type SendSingleFacecamNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSingleFacecamNotificationResponse) Reset() {
	*x = SendSingleFacecamNotificationResponse{}
	mi := &file_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSingleFacecamNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSingleFacecamNotificationResponse) ProtoMessage() {}

func (x *SendSingleFacecamNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSingleFacecamNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendSingleFacecamNotificationResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *SendSingleFacecamNotificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendSingleFacecamNotificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x11photo/photo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"d\n" +
	"\x14AuthenticateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".user.UserR\x04user\"\x81\x01\n" +
	"\x15AuthenticateRequestV2\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"f\n" +
	"\x16AuthenticateResponseV2\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".user.UserR\x04user\"\xd0\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x1e\n" +
	"\n" +
	"similarity\x18\x05 \x01(\rR\n" +
	"similarity\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x06 \x01(\tR\tcreatorId\x12\x1b\n" +
	"\twallet_id\x18\a \x01(\tR\bwalletId\"\xa8\x01\n" +
	"\x1bSendBulkNotificationRequest\x12L\n" +
	"\tcount_map\x18\x01 \x03(\v2/.user.SendBulkNotificationRequest.CountMapEntryR\bcountMap\x1a;\n" +
	"\rCountMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"L\n" +
	"\x1cSendBulkNotificationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	" SendBulkPhotoNotificationRequest\x12R\n" +
	"\x17bulk_user_similar_photo\x18\x01 \x03(\v2\x1b.photo.BulkUserSimilarPhotoR\x14bulkUserSimilarPhoto\"Q\n" +
	"!SendBulkPhotoNotificationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"k\n" +
	"\"SendSinglePhotoNotificationRequest\x12E\n" +
	"\x12user_similar_photo\x18\x01 \x03(\v2\x17.photo.UserSimilarPhotoR\x10userSimilarPhoto\"S\n" +
	"#SendSinglePhotoNotificationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"m\n" +
	"$SendSingleFacecamNotificationRequest\x12E\n" +
	"\x12user_similar_photo\x18\x01 \x03(\v2\x17.photo.UserSimilarPhotoR\x10userSimilarPhoto\"U\n" +
	"%SendSingleFacecamNotificationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xdc\x04\n" +
	"\vUserService\x12E\n" +
	"\fAuthenticate\x12\x19.user.AuthenticateRequest\x1a\x1a.user.AuthenticateResponse\x12K\n" +
	"\x0eAuthenticateV2\x12\x1b.user.AuthenticateRequestV2\x1a\x1c.user.AuthenticateResponseV2\x12l\n" +
	"\x19SendBulkPhotoNotification\x12&.user.SendBulkPhotoNotificationRequest\x1a'.user.SendBulkPhotoNotificationResponse\x12r\n" +
	"\x1bSendSinglePhotoNotification\x12(.user.SendSinglePhotoNotificationRequest\x1a).user.SendSinglePhotoNotificationResponse\x12]\n" +
	"\x14SendBulkNotification\x12!.user.SendBulkNotificationRequest\x1a\".user.SendBulkNotificationResponse\x12x\n" +
	"\x1dSendSingleFacecamNotification\x12*.user.SendSingleFacecamNotificationRequest\x1a+.user.SendSingleFacecamNotificationResponseB;Z9github.com/hervibest/be-yourmoments-backup/pb/user;userpbb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_user_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),                   // 0: user.AuthenticateRequest
	(*AuthenticateResponse)(nil),                  // 1: user.AuthenticateResponse
	(*AuthenticateRequestV2)(nil),                 // 2: user.AuthenticateRequestV2
	(*AuthenticateResponseV2)(nil),                // 3: user.AuthenticateResponseV2
	(*User)(nil),                                  // 4: user.User
	(*SendBulkNotificationRequest)(nil),           // 5: user.SendBulkNotificationRequest
	(*SendBulkNotificationResponse)(nil),          // 6: user.SendBulkNotificationResponse
	(*SendBulkPhotoNotificationRequest)(nil),      // 7: user.SendBulkPhotoNotificationRequest
	(*SendBulkPhotoNotificationResponse)(nil),     // 8: user.SendBulkPhotoNotificationResponse
	(*SendSinglePhotoNotificationRequest)(nil),    // 9: user.SendSinglePhotoNotificationRequest
	(*SendSinglePhotoNotificationResponse)(nil),   // 10: user.SendSinglePhotoNotificationResponse
	(*SendSingleFacecamNotificationRequest)(nil),  // 11: user.SendSingleFacecamNotificationRequest
	(*SendSingleFacecamNotificationResponse)(nil), // 12: user.SendSingleFacecamNotificationResponse
	nil,                                // 13: user.SendBulkNotificationRequest.CountMapEntry
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*photo.BulkUserSimilarPhoto)(nil), // 15: photo.BulkUserSimilarPhoto
	(*photo.UserSimilarPhoto)(nil),     // 16: photo.UserSimilarPhoto
}
var file_user_user_proto_depIdxs = []int32{
	4,  // 0: user.AuthenticateResponse.user:type_name -> user.User
	14, // 1: user.AuthenticateRequestV2.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 2: user.AuthenticateResponseV2.user:type_name -> user.User
	13, // 3: user.SendBulkNotificationRequest.count_map:type_name -> user.SendBulkNotificationRequest.CountMapEntry
	15, // 4: user.SendBulkPhotoNotificationRequest.bulk_user_similar_photo:type_name -> photo.BulkUserSimilarPhoto
	16, // 5: user.SendSinglePhotoNotificationRequest.user_similar_photo:type_name -> photo.UserSimilarPhoto
	16, // 6: user.SendSingleFacecamNotificationRequest.user_similar_photo:type_name -> photo.UserSimilarPhoto
	0,  // 7: user.UserService.Authenticate:input_type -> user.AuthenticateRequest
	2,  // 8: user.UserService.AuthenticateV2:input_type -> user.AuthenticateRequestV2
	7,  // 9: user.UserService.SendBulkPhotoNotification:input_type -> user.SendBulkPhotoNotificationRequest
	9,  // 10: user.UserService.SendSinglePhotoNotification:input_type -> user.SendSinglePhotoNotificationRequest
	5,  // 11: user.UserService.SendBulkNotification:input_type -> user.SendBulkNotificationRequest
	11, // 12: user.UserService.SendSingleFacecamNotification:input_type -> user.SendSingleFacecamNotificationRequest
	1,  // 13: user.UserService.Authenticate:output_type -> user.AuthenticateResponse
	3,  // 14: user.UserService.AuthenticateV2:output_type -> user.AuthenticateResponseV2
	8,  // 15: user.UserService.SendBulkPhotoNotification:output_type -> user.SendBulkPhotoNotificationResponse
	10, // 16: user.UserService.SendSinglePhotoNotification:output_type -> user.SendSinglePhotoNotificationResponse
	6,  // 17: user.UserService.SendBulkNotification:output_type -> user.SendBulkNotificationResponse
	12, // 18: user.UserService.SendSingleFacecamNotification:output_type -> user.SendSingleFacecamNotificationResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
