apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
  labels:
    app: notification-svc
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
        version: v1
    spec:
      containers:
      - name: notification-svc
        image: ghcr.io/hervipro/be-yourmoments-backup-notification-svc:latest
        ports:
        - containerPort: 8004
        env:
        - name: PORT
          value: "8004"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: db-name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: redis-password
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: nats-url
        - name: CONSUL_HOST
          valueFrom:
            secretKeyRef:
              name: notification-svc-secrets
              key: consul-host
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/serviceAccountKey.json"
        volumeMounts:
        - name: service-account-key
          mountPath: /app/serviceAccountKey.json
          subPath: serviceAccountKey.json
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: service-account-key
        secret:
          secretName: notification-svc-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  selector:
    app: notification-svc
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
  type: ClusterIP
