apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-svc
  labels:
    app: photo-svc
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-svc
  template:
    metadata:
      labels:
        app: photo-svc
        version: v1
    spec:
      containers:
      - name: photo-svc
        image: ghcr.io/hervipro/be-yourmoments-backup-photo-svc:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: db-name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: redis-password
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: nats-url
        - name: CONSUL_HOST
          valueFrom:
            secretKeyRef:
              name: photo-svc-secrets
              key: consul-host
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: photo-svc
  labels:
    app: photo-svc
spec:
  selector:
    app: photo-svc
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
