apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-svc
  labels:
    app: transaction-svc
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-svc
  template:
    metadata:
      labels:
        app: transaction-svc
        version: v1
    spec:
      containers:
      - name: transaction-svc
        image: ghcr.io/hervipro/be-yourmoments-backup-transaction-svc:latest
        ports:
        - containerPort: 8005
        env:
        - name: PORT
          value: "8005"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: db-name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: redis-password
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: nats-url
        - name: CONSUL_HOST
          valueFrom:
            secretKeyRef:
              name: transaction-svc-secrets
              key: consul-host
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-svc
  labels:
    app: transaction-svc
spec:
  selector:
    app: transaction-svc
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
  type: ClusterIP
