apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-svc
  labels:
    app: upload-svc
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-svc
  template:
    metadata:
      labels:
        app: upload-svc
        version: v1
    spec:
      containers:
      - name: upload-svc
        image: ghcr.io/hervipro/be-yourmoments-backup-upload-svc:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: db-name
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: minio-endpoint
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: minio-secret-key
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: nats-url
        - name: CONSUL_HOST
          valueFrom:
            secretKeyRef:
              name: upload-svc-secrets
              key: consul-host
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: upload-svc
  labels:
    app: upload-svc
spec:
  selector:
    app: upload-svc
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
