// Code generated by MockGen. DO NOT EDIT.
// Source: ./adapter/cache_adapter.go
//
// Generated by this command:
//
//	mockgen -source=./adapter/cache_adapter.go -destination=./mocks/adapter/mock_cache_adapter.go -package=mockadapter
//

// Package mockadapter is a generated GoMock package.
package mockadapter

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheAdapter is a mock of CacheAdapter interface.
type MockCacheAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockCacheAdapterMockRecorder
	isgomock struct{}
}

// MockCacheAdapterMockRecorder is the mock recorder for MockCacheAdapter.
type MockCacheAdapterMockRecorder struct {
	mock *MockCacheAdapter
}

// NewMockCacheAdapter creates a new mock instance.
func NewMockCacheAdapter(ctrl *gomock.Controller) *MockCacheAdapter {
	mock := &MockCacheAdapter{ctrl: ctrl}
	mock.recorder = &MockCacheAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheAdapter) EXPECT() *MockCacheAdapterMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheAdapter) Del(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacheAdapterMockRecorder) Del(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheAdapter)(nil).Del), varargs...)
}

// Get mocks base method.
func (m *MockCacheAdapter) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheAdapterMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheAdapter)(nil).Get), ctx, key)
}

// HDel mocks base method.
func (m *MockCacheAdapter) HDel(ctx context.Context, key string, fields ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HDel", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HDel indicates an expected call of HDel.
func (mr *MockCacheAdapterMockRecorder) HDel(ctx, key any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HDel", reflect.TypeOf((*MockCacheAdapter)(nil).HDel), varargs...)
}

// HMGet mocks base method.
func (m *MockCacheAdapter) HMGet(ctx context.Context, key string, fields ...string) ([]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HMGet", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HMGet indicates an expected call of HMGet.
func (mr *MockCacheAdapterMockRecorder) HMGet(ctx, key any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HMGet", reflect.TypeOf((*MockCacheAdapter)(nil).HMGet), varargs...)
}

// HSet mocks base method.
func (m *MockCacheAdapter) HSet(ctx context.Context, key string, values ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockCacheAdapterMockRecorder) HSet(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockCacheAdapter)(nil).HSet), varargs...)
}

// SAdd mocks base method.
func (m *MockCacheAdapter) SAdd(ctx context.Context, key string, members ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SAdd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SAdd indicates an expected call of SAdd.
func (mr *MockCacheAdapterMockRecorder) SAdd(ctx, key any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SAdd", reflect.TypeOf((*MockCacheAdapter)(nil).SAdd), varargs...)
}

// Set mocks base method.
func (m *MockCacheAdapter) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheAdapterMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheAdapter)(nil).Set), ctx, key, value, expiration)
}

// TTL mocks base method.
func (m *MockCacheAdapter) TTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockCacheAdapterMockRecorder) TTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockCacheAdapter)(nil).TTL), ctx, key)
}
