// Code generated by MockGen. DO NOT EDIT.
// Source: ./adapter/google_token_adapter.go

// Package mockadapter is a generated GoMock package.
package mockadapter

import (
	model "github.com/hervibest/be-yourmoments-backup/user-svc/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoogleTokenAdapter is a mock of GoogleTokenAdapter interface.
type MockGoogleTokenAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleTokenAdapterMockRecorder
}

// MockGoogleTokenAdapterMockRecorder is the mock recorder for MockGoogleTokenAdapter.
type MockGoogleTokenAdapterMockRecorder struct {
	mock *MockGoogleTokenAdapter
}

// NewMockGoogleTokenAdapter creates a new mock instance.
func NewMockGoogleTokenAdapter(ctrl *gomock.Controller) *MockGoogleTokenAdapter {
	mock := &MockGoogleTokenAdapter{ctrl: ctrl}
	mock.recorder = &MockGoogleTokenAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleTokenAdapter) EXPECT() *MockGoogleTokenAdapterMockRecorder {
	return m.recorder
}

// GetClientId mocks base method.
func (m *MockGoogleTokenAdapter) GetClientId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetClientId indicates an expected call of GetClientId.
func (mr *MockGoogleTokenAdapterMockRecorder) GetClientId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientId", reflect.TypeOf((*MockGoogleTokenAdapter)(nil).GetClientId))
}

// ValidateGoogleToken mocks base method.
func (m *MockGoogleTokenAdapter) ValidateGoogleToken(ctx context.Context, token string) (*model.GoogleSignInClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateGoogleToken", ctx, token)
	ret0, _ := ret[0].(*model.GoogleSignInClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateGoogleToken indicates an expected call of ValidateGoogleToken.
func (mr *MockGoogleTokenAdapterMockRecorder) ValidateGoogleToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateGoogleToken", reflect.TypeOf((*MockGoogleTokenAdapter)(nil).ValidateGoogleToken), ctx, token)
}
